#ifndef _SYMBOLS_H_
#define _SYMBOLS_H_
#define BODYOPEN 
#define BODYCLOSE 
#define FRAMEOPEN 
#define FRAMECLOSE 
#define FRAMESETOPEN 
#define FRAMESETCLOSE 
#define NOFRAMESOPEN 
#define NOFRAMESCLOSE 
#define FORMOPEN 
#define FORMCLOSE 
#define INPUTOPEN 
#define INPUTCLOSE 
#define SELECTOPEN 
#define SELECTCLOSE 
#define OPTIONOPEN 
#define OPTIONCLOSE 
#define TABLEOPEN 
#define TABLECLOSE 
#define TROPEN 
#define TRCLOSE 
#define TDOPEN 
#define TDCLOSE 
#define THOPEN 
#define THCLOSE
#define THEAD 
#define TBODY 
#define IMG 
#define AOPEN 
#define ACLOSE 
#define LINKOPEN
#define LINKCLOSE
#define ULOPEN 
#define ULCLOSE 
#define LIOPEN 
#define LICLOSE 
#define OLOPEN 
#define OLCLOSE 
#define BOPEN 
#define BCLOSE 
#define IOPEN 
#define ICLOSE 
#define UOPEN 
#define UCLOSE 
#define SMALLOPEN 
#define SMALLCLOSE 
#define SUPOPEN 
#define SUPCLOSE 
#define SUBOPEN 
#define SUBCLOSE 
#define CENTEROPEN
#define CENTERCLOSE
#define FONTOPEN 
#define FONTCLOSE 
#define HNOPEN 
#define HNCLOSE 
#define HROPEN
#define HRCLOSE
#define POPEN 
#define PCLOSE 
#define BROPEN
#define BRCLOSE
#define ALIGN 
#define SIZE 
#define WIDTH 
#define NOSHADE 
#define NAME 
#define REL 
#define REV 
#define TITLE 
#define URN 
#define METHODS 
#define SHAPE 
#define COORDS 
#define ALT 
#define NOHREF 
#define BGCOLOR 
#define BACKGROUND 
#define TEXT 
#define LINK 
#define VLINK 
#define ALINK 
#define VERSION 
#define COLOR 
#define CLEAR 
#define ACTION 
#define ENCTYPE 
#define METHOD 
#define SRC 
#define HEIGHT 
#define SPACE 
#define VSPACE 
#define BORDER 
#define USEMAP 
#define ISMAP 
#define TYPE 
#define VALUE 
#define MAXLENGTH 
#define CHECKED 
#define PROMPT 
#define ID 
#define HTTPEQUIV 
#define CONTENT 
#define START 
#define SELECTED 
#define MULTIPLE 
#define CELLSPACING 
#define CELLPADDING 
#define VALIGN 
#define ROWSPAN 
#define COLSPAN 
#define NOWRAP 
#define ROWS 
#endif

